### ISSUE TITLE
Simplify deployment as a monolithic app

### ISSUE THREAD

**Issue by millerh1** [Bioinformatics-Research-Network/Bioinformed-Skill-App#44]
Currently we deploy 3 services separately (`ghbot`, `crud`, and `webui`). However this is expensive and unnecessary for the stage we are at today with this app. Instead, we should develop a push-button deploy workflow for all three services to the same elastic beanstalk instance. This could use docker compose in order to orchestrate them within each EC2.

The structure could be like this:

```YML
EB-Docker-Image:
  docker-compose:
    crud:
      image: crud-image on ECR
    ghbot:
      image: ghbot-image on ECR
    webui:
      image: webui-image on ECR
```
